// react/src/components/CommentForm/index.tsx
import * as React from "react";
import {FunctionComponent} from "react";
import {
    Link
} from "react-router-dom";

import './_commentform.scss';
import profile_img from '../../assets/images/profile1.png';

const CommentForm: FunctionComponent = () => {

    return (
        <div className="comment-form">
            <form action="" className="form">
                <div className="container">
                    <div className="row justify-content-md-center">
                        <div className="col-md-10">
                            <div className="row">
                                <div className="col-2 col-md-2 left">
                                    <div className="profile">
                                        <Link to={'/portal'}>
                                            <img src={profile_img} className="img" alt="" />
                                        </Link>
                                    </div>
                                </div>
                                <div className="col">
                                    <input type="text" className="text" placeholder="Write something…"/>
                                </div>
                                <div className="col-12 col-md-3">
                                    <button className="big-button" type="submit">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    )
}

export default CommentForm;

// vue/src/components/CommentForm.vue
<template>
    <div class="comment-form">
        <form action="/portal" class="form">
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-2 col-md-2 left">
                                <div class="profile">
                                    <router-link to="/portal">
                                        <img src="../assets/images/profile1.png" class="img" alt="" />
                                    </router-link>
                                </div>
                            </div>
                            <div class="col">
                                <input type="text" class="text" placeholder="Write something…"/>
                            </div>
                            <div class="col-12 col-md-3">
                                <button class="big-button" type="submit">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</template>

<script lang="ts">
import {Component, Vue} from 'vue-property-decorator';


@Component
export default class CommentForm extends Vue {
    
}

</script>

<style lang="scss">
@import "~bootstrap/scss/_functions.scss";
@import "~bootstrap/scss/_variables.scss";
@import "~bootstrap/scss/mixins/_breakpoints.scss";


.comment-form {
    background: #eeeef2;
    padding: 0 0 58px 0;

    .form {
        .left {
            text-align: left;

            @include media-breakpoint-up(md) {
                text-align: center;
            }
        }

        .profile .img {
            max-width: 60px;
            border-radius: 50%;
            display: inline-block;
        }

        .text {
            width: 100%;
            background: #fff;
            border-radius: 30px;
            color: #3C3E46;
            font-family: "Maison Neue", sans-serif;
            font-size: 18px;
            font-weight: 300;
            letter-spacing: 0;
            line-height: 24px;
            opacity: 1;
            margin: 0;
            border: none;
            padding: 19px 0;
            text-indent: 30px;

            @include media-breakpoint-up(md) {
                width: 100%;
            }

            @include media-breakpoint-up(lg) {
                width: 110%;
                margin: 0 0 0 -35px;
            }

            &::placeholder {
                opacity: 0.6;
            }

            &:focus {
                outline: none;
                box-shadow: 0 0 0 3px #6648cd;
            }
        }

        .big-button {
            width: 100%;
            display: block;
            border: none;
            color: #FFFFFF;
            font-family: "Maison Neue", sans-serif;
            font-size: 18px;
            font-weight: 500;
            letter-spacing: 0;
            line-height: 24px;
            background: #6648cd;
            padding: 19px 0;
            border-radius: 30px;
            max-width: 100%;
            margin: 20px 0 0 0;

            @include media-breakpoint-up(sm) {
                margin: 0 0 0 13px;
            }

            @include media-breakpoint-up(lg) {
                max-width: 161px;
                margin: 0 0 0 13px;
            }

            &:focus {
                outline: none;
            }
        }
    }
}
</style>
